### ISSUE TITLE
Upgrade repo to Ceph-Nautilus

### ISSUE THREAD

**Issue by jlefevre** [uccross/skyhookdm-ceph-cls#13]
Move from Luminous to Nautilus.  Although Octopus stable version was [just released ](https://ceph.io/releases/v15-2-0-octopus-released/)we will wait on this for more user adoption.

**Comment by ivotron** [comment]
currently, moving the parent repo from luminous to nautilus causes the following error: https://travis-ci.com/github/uccross/skyhookdm-ceph-cls/builds/168964597

**Comment by ivotron** [comment]
From @jlefevre :

> it seems they just changed the signature of encode  to explicitly specify the type as 3rd arg (e.g., uint64_t) whereas it used to be implicitly inferred.  i'll work on that error first, seems reasonable to fix.

**Comment by ivotron** [comment]
this issue is blocking the progress of the [Hello World](https://github.com/uccross/skyhookdm-ceph-cls/projects/1) project. At this point we cannot deploy rook unless we're able to run on Nautilus.

In addition, new features/fixes are still being developed on the luminous branch (e.g. #41), which means there's technical debt being accumulated, since those changes will need to be ported to nautilus as well since now they're on separate branches.

Is there anything we can do to help with this?

**Comment by jlefevre** [comment]
I merged PR #45  , all working now in popper env, so this should unblock Jayjeet.   I'm leaving this open for now since there is still a problem with vstart, which we also use for development, so will continue working on that part.
